### ISSUE TITLE
Error: gas required exceeds allowance (10000000) or always failing transaction

### ISSUE THREAD

**Issue by jonpurdy** [futureswap/liquidation_bot#3]
Seeing these every few minutes:
```
api_1       | info: Liquidation check at 1583504142738
api_1       | (node:28) UnhandledPromiseRejectionWarning: Error: gas required exceeds allowance (10000000) or always failing transaction
api_1       |     at getResult (/home/node/node_modules/ethers/providers/json-rpc-provider.js:40:21)
```

See this for four fully logged events: [log.txt](https://github.com/futureswap/liquidation_bot/files/4299641/log.txt)

**Comment by JesseAbram** [comment]
Yup this is from ethers catching a failing tx, usually an already closed trade, could be from our bots competing. Not a huge issue but I should wrap it in a try catch and put a better error message

**Comment by JesseAbram** [comment]
hmmm I looked and it seems my bot is also doing that, but when I restart it the issue goes away, my best guess is that it missed a closing event and is now throwing the error. I think the best thing would be a try catch and on the catch check if the tradeId is closed and if so close it in the DB

**Comment by JesseAbram** [comment]
https://github.com/futureswap/liquidation_bot/pull/6

**Comment by JesseAbram** [comment]
https://github.com/futureswap/liquidation_bot/pull/6
