### ISSUE TITLE
Human-readable datetime logging

### ISSUE THREAD

**Issue by jonpurdy** [futureswap/liquidation_bot#4]
`info: Liquidation check at 1583504142738`

Recommended to just do ISO-8601 UTC: 2020-03-06T17:40:22Z

**Comment by JesseAbram** [comment]
Yup makes sense!

**Comment by JesseAbram** [comment]
![image](https://user-images.githubusercontent.com/33698952/76227832-470b6680-61f6-11ea-888b-2eb545093c3b.png)
with the ability to chose your timezone

**Comment by JesseAbram** [comment]
https://github.com/futureswap/liquidation_bot/pull/7
